### ISSUE TITLE
Saving happens way too often

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#134]
1. We should only save the active road (I don't see a way for any of the other roads to have changed)
2. It seems like roads get saved twice, at least at the beginning (same with updateFulfillment)

**Comment by npfoss** [comment]
Is this still a problem after the speed improvements PR? That cut down on it some, right?

**Comment by georgiashay** [comment]
This should be fixed with the speed improvements PR

**Comment by npfoss** [comment]
great
