### ISSUE TITLE
Review all wording and copy

### ISSUE THREAD

**Issue by wishdasher** [sipb/courseroad2#175]
In particular, "No problems detected!" sounds weird to me right now.

"Select all" and "Select any"

**Comment by npfoss** [comment]
I agree that the word select makes it sound like you're supposed to click them or something

**Comment by georgiashay** [comment]
The select wording comes straight from fireroad, but it wouldn't be too hard to put our own in instead

**Comment by georgiashay** [comment]
Reviewed
