### ISSUE TITLE
FireRoad road incompatibility?

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#180]
I just had a FireRoad for iOS user login to a version of CourseRoad which points to the fireroad-dev backend, and got these errors and a blank road:
![image](https://user-images.githubusercontent.com/10506482/56341731-f6c18b00-6183-11e9-9bf4-a0bc5f3a5a72.png)

**Comment by npfoss** [comment]
Please test on your friends, it's unclear whether this is still a problem and how significant of a problem it is

**Comment by georgiashay** [comment]
¯\_(ツ)_/¯
