### ISSUE TITLE
Weird things happening when you press back

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#196]
Was informed that a user pressed the back button from the about page and the following happened:

their mouse flickered between pointer and grabby hand
they were unable to click on anything

**Comment by npfoss** [comment]
Can't reproduce, but I did find that if you go to the about page and press back (to main page) and then forward (should take you to about page) you stay on the main page. I think that's totally fine though

**Comment by georgiashay** [comment]
Other things weren't working for this user, and clearing cache and going incognito cleared those up so this could have been a one off

**Comment by georgiashay** [comment]
Can't reproduce, haven't seen since
