### ISSUE TITLE
add to about page:

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#208]
- [x] Thank the Office of the First Year (Kate)
- [x] say something about it always being a work in progress, so more features are coming and feel free to help make them

**Comment by wishdasher** [comment]
Should I also add something about SIPB?

**Comment by wishdasher** [comment]
Done with #233

**Comment by npfoss** [comment]
Sorry for being unresponsive. I agree with all of your choices, thanks for doing this
