### ISSUE TITLE
Audit took >20s to update

### ISSUE THREAD

**Issue by wishdasher** [sipb/courseroad2#210]
Also I don't think things are being saved in local cookies

![image](https://user-images.githubusercontent.com/9587565/56710492-6ee3ff80-66f4-11e9-9473-cff62bbc831a.png)

For 6.0001 specifically

**Comment by ttpcodes** [comment]
The cookies thing should probably be a separate issue if that's something you also ran into. I ran into a friend this morning who said that after logging in, the road they made before logging in was gone, and they had to start again from scratch.

**Comment by georgiashay** [comment]
^ I think we need to make it clear that if you don't allow cookies before logging in, we have no way of storing the road locally, and it will not be saved and uploaded on login.  There could be an issue with roads uploading after login, but it seems more likely that the banner just isn't being accepted first.

**Comment by georgiashay** [comment]
Doesn't take that long anymore, creating separate issue for performance in general
