### ISSUE TITLE
undefined subjects in road

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#215]
It's possible for the `subj` variable in `classSatisfies` in `Semester.vue` to be undefined, and that caused the following minor errors:
![image](https://user-images.githubusercontent.com/10506482/56789977-41b94f00-67d1-11e9-8706-338394bc09c0.png)

This is because the subject of interest is neither in `allSubjects` or `genericCourses`. I'm not sure what we want to do about that. The solution is probably to add more legacy classes to `allSubjects`?

**Comment by npfoss** [comment]
I pushed the two-line fix to master since I want to deploy tonight, but we should actually solve the root of the problem

**Comment by georgiashay** [comment]
Does this happen because of the catalog update?  I.e. the subject was added previously but is no longer in the catalog?

**Comment by npfoss** [comment]
That seems likely

**Comment by georgiashay** [comment]
Fixed, historical classes
