### ISSUE TITLE
wacky search placement

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#216]
On the dev site (the errors are unrelated, mentioned in #215):
![image](https://user-images.githubusercontent.com/10506482/56790304-3ca8cf80-67d2-11e9-89d1-4915ad46e382.png)

On localhost (note the offset):
![image](https://user-images.githubusercontent.com/10506482/56790331-4c281880-67d2-11e9-8f15-49301b1a09db.png)

They both went away upon resizing the screen.

The offset happens when you reload with inspect element open, but I have no idea how to reproduce the first one..

**Comment by georgiashay** [comment]
I am updating positioning on resize.  Does opening inspect element not trigger window.resize?

**Comment by npfoss** [comment]
It's if inspect element is already open when I reload. It does the right thing on page resize, including resize caused by opening that.

**Comment by georgiashay** [comment]
The search also scrolls with the roads, which shouldn't happen

**Comment by wishdasher** [comment]
Search menu scrolls with the road.

**Comment by npfoss** [comment]
Oh hm that's actually a big problem

**Comment by georgiashay** [comment]
Probably better to not use jquery for positioning (seems like all errors are due to this), but not sure how to position it without placing it around the text field, which caused other problems.

**Comment by npfoss** [comment]
Hm ok well let's figure it out as soon as #239 goes in

**Comment by georgiashay** [comment]
ok i am legit so confused on this.  I tried a bunch of things to get it to work without jquery with no success, so I set the jquery to update on scroll and subtract $(window).scrollTop.  If I subtract 0.99 * that, it looks very close to correct, 0.999 looks closer, etc, but if I just subtract the whole thing it becomes completely off again.  I have no idea what is going on but it's probably some weird javascript thing??

**Comment by npfoss** [comment]
hm, a) I feel like this should definitely be possible without updating on scroll and b) wtf javascript...

**Comment by georgiashay** [comment]
I think this might be possible with the input-activator prop.  When set it uses the activator slot to determine when to open instead of v model, and also seems to position it properly.  I think this would involve creating a custom component that emits an input event on both click and type.  I did try something like this already but it would probably work with more tweaking.

This would break some ui stuff with the size of the input, but hopefully with the right combination of layouts and flexes it would be ok.
