### ISSUE TITLE
Handle expected hours differently for quarter classes

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#224]
Right now it just adds them so if you have two quarter classes that take 10 hours each it will say 20 hours even though you will have no more than 10 hours at a time.

I think we should probably check both quarters, and take the maximum total hours for each quarter.  That way if you take 2 quarter classes in the same quarter it _will_ add them together. 
 Either way it should be documented somewhere so users know what is being calculated.

**Comment by georgiashay** [comment]
Also adding to this that we should also use units as hours if they are no expected hours

**Comment by npfoss** [comment]
did #248 just resolve this? I think it had everything but the documentation bit

**Comment by georgiashay** [comment]
Yeah resolved except for documentation.  Not sure where we should put that that wouldn't cause extra clutter?

**Comment by npfoss** [comment]
I'm not sure either. Maybe we should just wait for the first person to send us a confused email, ask them where they looked first upon becoming confused, and then put it there?

**Comment by georgiashay** [comment]
Sounds like the best approach

**Comment by georgiashay** [comment]
Tooltip to show breakdown of hours across quarters (possibly in a 1-2 column table)
