### ISSUE TITLE
Annoying closure of search menu

### ISSUE THREAD

**Issue by wishdasher** [sipb/courseroad2#234]
- search for class
- click on it to open info card
- close info card

The search results also disappear. I don't think they should in this case.

**Comment by npfoss** [comment]
I agree this is annoying. It should just be as simple as not letting the click event escape the info card I think

Another annoying closure is when you delete all of your input it goes away, making searches with filters hard

**Comment by georgiashay** [comment]
Looks like there is already an $event.stopPropagation, so this is weird behavior

**Comment by georgiashay** [comment]
No longer happening
