### ISSUE TITLE
handle invalid urls better

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#236]
Hi Courseroad Team,

When I go to http://courseroad.mit.edu, it redirects to this: http://courseroad.mit.edu/#/#road$defaultroad$, but then if I try to copy and paste that link and open it, it goes to this: http://courseroad.mit.edu/#/%23road$defaultroad$ which is a blank page.

Is this a solvable problem? I foresee many non-techy people trying to copy the URL from their browser to share with an advisor or advisee (or colleague) and concluding that it’s broken. Let me know if this is something that can be addressed. 

Thanks,
Kate

**Comment by npfoss** [comment]
note to self: seems like we should just check if `roadID` is legal/defined in the right place, and set it/redirect to default if not

**Comment by georgiashay** [comment]
Should be byproduct of #312
