### ISSUE TITLE
Off by 1 error: Indicating freshman starts road at Fall 2019

### ISSUE THREAD

**Issue by wishdasher** [sipb/courseroad2#238]
Fix fix fix

**Comment by georgiashay** [comment]
It's possible the semesters rolled over in May

**Comment by georgiashay** [comment]
Yep, it looks like we have it set to assume your class year changes in May.  I copied from Fireroad for this [here](https://github.com/venkatesh-sivaraman/FireRoad-Android/blob/cdb736aa1c77f6cb07e5bbb884e2482ce008e5be/app/src/main/java/com/base12innovations/android/fireroad/models/course/CourseManager.java#L967).  It would probably make more sense to update in June instead?

**Comment by venkatesh-sivaraman** [comment]
FireRoad uses the current semester to represent what the user is planning for, e.g. in May they’re probably planning their next fall. The wording is “Choose your current (upcoming) class year.” But since you guys are actually displaying the years, that could get confusing- I’m not sure what the best solution is. I do feel that displaying the calendar years isn’t really necessary (and gets confusing with gap years), but if you want to keep that, it probably wouldn’t be too difficult to make your own semester calculation that interconverts with FireRoad’s.

**Comment by georgiashay** [comment]
I think I'd actually rather have it just show the year name (freshman/sophomore/junior/senior) and not the real year.  It takes care of edge cases like gap years and I don't think the calendar year adds much, but I do think we said it was important to include so I'm not sure how others feel about this.  Personally it's easier to think in terms of class year than calendar year when planning my road.

**Comment by npfoss** [comment]
Calendar year is very important so that we can warn people about subjects "not offered '20-'21". I don't think it's important that we display it, but it is important to get right. Also, I agree that semantic term names would be nice

**Comment by npfoss** [comment]
What if we changed the thing to ask "what year did you start?" This removes a lot of ambiguity on both sides.

**Comment by georgiashay** [comment]
That would make class year clearer I think.

For the May vs a June thing I think the best course of action would be to convert the FireRoad semester to our own that rolls over in June?

**Comment by npfoss** [comment]
How does this actually look right now in what we're getting and saving? Is it just `current-semester: index` thing? `freshman/sophomore/junior/senior`? How does that get incremented every term?

**Comment by georgiashay** [comment]
When you change your class year, it will update the FireRoad current semester based on the time of year.  FireRoad also increments your current semester when the time of year changes.  So right now my current FireRoad semester would be 4 for Fall 2019, and I think we should just be able to subtract 1 when we receive that from the server and add 1 when we push to the server and have everything still work properly.

**Comment by npfoss** [comment]
Ok did a temporary fix on #223, pushed it to /dev/ and it seemed to work, so I'm pushing it to prod. Let me know if you see any problems.
