### ISSUE TITLE
add warning if subject planned for next semester doesn't have a schedule yet

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#252]
According to Anne Hunter, at this point that means the class likely won't be offered next semester

**Comment by georgiashay** [comment]
What should the cutoff point be?  Something like 2 weeks after last month of previous semester?

**Comment by npfoss** [comment]
Hmm definitely by the prereg deadline... which is usually like 2 months prior to the next semester? Right?

**Comment by npfoss** [comment]
oops actually this doesn't work right. see 18.335, a spring-only class which currently has this warning. @georgiashay can you take a look please?

**Comment by npfoss** [comment]
actually fixed now
