### ISSUE TITLE
HASS-E???

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#255]
Hi,

I noticed one of my future HASS Classes, 21L.590, does not show up as a valid HASS course to satisfy the requirement. I checked with the HASS department, and they confirmed that it is a 9 unit HASS-E that should count as an elective. Is there anything I can do to see that on the Course Road?

Thanks,
Nicholas Fritzinger-Pittman

**Comment by georgiashay** [comment]
@venkatesh-sivaraman, does the course catalog parser handle HASS-E classes right now?  If not, how hard would this be to add?

**Comment by venkatesh-sivaraman** [comment]
The dev server now provides a HASS-E designation - I'll be moving this to prod once I've ensured compatibility with the mobile apps.

**Comment by npfoss** [comment]
Looks like this is resolved. The only remaining question is if we want to do anything else with HASS-Es, like add a search filter button. I'm against this since it shows up already with the 'any hass' filter, so I'm going to close the issue and we can open a new one for that particular thing if need be.
