### ISSUE TITLE
Add subjectsInfo cookie

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#257]
Add a cookie with subjectsInfo that can be used before it loads from the API

**Comment by georgiashay** [comment]
Update: the object is way too big to be stored in a cookie

**Comment by npfoss** [comment]
What about localstorage? I've heard of people dumping Vuex state there and then reloading it when the user comes back. There might even be a built in way to do that?

**Comment by miriam-rittenberg** [comment]
I think it's too large for localStorage as well

**Comment by npfoss** [comment]
[discussed at courseroad meeting]

resolution, for the record:
store subjectInfo with empty course descriptions (since those are big and not immediately essential) and load the full data in the background
