### ISSUE TITLE
Improved handling of partial subjects

### ISSUE THREAD

**Issue by venkatesh-sivaraman** [sipb/courseroad2#262]
FYI that I've implemented a better way to handle partial subjects (for example, 6.0001 + 6.0002 = 6.00). This was completed for the frontend's prereq computation in #135, I believe - but back then we had to hardcode those subjects, which wasn't ideal. Now each subject can have optional `parent` and `children` keys to specify which courses can add together to satisfy another course. For example, 6.0001 and 6.0002 each have `"parent": "6.00"`, and 6.00 has `"children": ["6.0001", "6.0002"]`. Other examples include 6.041A/B and 3.016A/B.

You can see how I've implemented the requirement checking [here](https://github.com/venkatesh-sivaraman/fireroad-server/blob/885a9a67fa48113e733b7f9f5cd000684bc6d69c/catalog/models.py#L428). This feature is currently on dev, and will soon move to prod.

**Comment by georgiashay** [comment]
This is great!  We can update our code to use the new keys, always good to get rid of hardcoded things.
