### ISSUE TITLE
Equivalent subjects don't count for prereqs 

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#270]
If a subject is equivalent to a subject needed for prereq, it should count for that prereq

Affected subjects include ESG subjects not fulfilling prereqs

**Comment by npfoss** [comment]
Note to self: I've been testing this with 7.32, which requires 18.05 and 18.03. So 18.05 + ES.1803 should satisfy that prereq. Works so far on the partial-subjects branch, but not master currently.
