### ISSUE TITLE
drag one class, a different one moves

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#276]
see this janky video: https://photos.app.goo.gl/6fjat8DYy1RYvKPP6
(taken 7/24, on master)

probably related to #268

**Comment by npfoss** [comment]
might be fixed by #264, I haven't seen it on that branch yet

**Comment by georgiashay** [comment]
Possibly related to #268?  Would have to look into this

**Comment by npfoss** [comment]
I think this was fixed by #264
