### ISSUE TITLE
petitions -- backend

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#278]
What do we need to implement on the fireroad side to support petitions/overrides? @venkatesh-sivaraman

**Comment by venkatesh-sivaraman** [comment]
The backend changes should be pretty straightforward. We should probably add a field to the road file that maps requirement elements (which we already have unique IDs for) to lists of courses that the user wants to override with. Then the `progress` endpoint just needs to look up the overrides, which it already does for manual progress items, and adjust its status accordingly. The only thing is that we would need to make the change on the backend as well as the two mobile apps.

**Comment by npfoss** [comment]
Cool, thanks. And since we're just adding another field/option to the existing road object, it shouldn't break anything (i.e. the current versions of the apps) that don't expect that field, right? It should just be ignored? (Just to confirm that we should change the backend first, then the web/mobile apps)
