### ISSUE TITLE
petitions

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#280]
This is the meta-issue for supporting petitions. (since there multiple parts)

We'd like to be able to choose a subject and a requirement and have it be allowed to fulfill that requirement the same as anything else. It might make sense to implement "pinning" at the same time, which is where you override the optimization engine or whatever and just say "use this subject for this req".

child issues:
- [ ] #278 
- [ ] #279

**Comment by npfoss** [comment]
Just added @kentslaney to the repo, he's interested in helping build this feature

**Comment by CyanoKobalamyne** [comment]
This has just been rolled out and made me realize that petitions are for specific subjects. (But if that's not the case, and I missed something, let me know.) However, I believe that most departments grant petitions to use a subject to fulfill a given requirement, which is similar to "substituting" a subject, but not quite the same thing.

E.g. 7.03 is a required subject for Course 7, so substituting a different subject here will work, but the Advanced Undergraduate Subject (AUS2) requirement of Course 6 covers a set of subjects, so if you petition a subject to count as AUS2, you are not petitioning to substitute it for a specific subject, but for the requirement in general. Of course, you could choose a subject from the list at random and add a petition for it, but that solution seems suboptimal.

**Comment by georgiashay** [comment]
@venkatesh-sivaraman can correct me if I am wrong, but I believe petitions are extendable to this without too much work.  Some things like that already work (i.e. the "two EECS subjects" requirement can be petitioned, as can other requirements of a similar nature) but it looks like right now petitioning is only available for bottom-level requirements (which excludes something like AUS2 for now).
