### ISSUE TITLE
bio major different on prod and dev

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#281]
On dev, bio's CIMs ("7 Major") are listed as this:
![image](https://user-images.githubusercontent.com/10506482/62803874-9f8c5100-bab9-11e9-8caa-ea763f4568de.png)
On the public site, however, it's this:
![image](https://user-images.githubusercontent.com/10506482/62803928-c77bb480-bab9-11e9-8f8b-4dca72cc86d3.png)
Which has way more options...

Any idea why that might be @venkatesh-sivaraman ? Or what else could be different?

**Comment by venkatesh-sivaraman** [comment]
Sorry for the delay- dev and prod have different database backends, and I usually don’t update dev as regularly. That shouldn’t interfere with testing, as requirements are essentially just config and not code. But let me know if you want it to be updated.

**Comment by npfoss** [comment]
Ah ok great, thanks. It hasn't caused any problems yet, I was just making sure it's purposeful.
