### ISSUE TITLE
not-offered-year is broken

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#286]
24.118 isn't offered this year, and it says so in `subjectsInfo`, but we aren't displaying a warning:
![image](https://user-images.githubusercontent.com/10506482/63228919-4e224700-c1c8-11e9-9857-f4342121d57c.png)

**Comment by georgiashay** [comment]
I think we are relying on is_historical right now so we don't handle classes which are transiently not offered.  It should just be a matter of adding the notCurrentlyOffered case in addition to the noLongerOffered case.
