### ISSUE TITLE
automatically log user back in after token expired

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#292]
"Have you thought about automatically going through the login flow if the user was logged in last time they used CourseRoad, but they’re not logged in now? Not sure how you implement this but you would probably just need a long-lived is_logged_in cookie in addition to the actual token."

--Venkat

Seconded

**Comment by georgiashay** [comment]
Just to clarify, do you mean redirecting to the login page if they were logged in last time but the token expired?

**Comment by venkatesh-sivaraman** [comment]
Right. It would (a) save you the extra click of the login button, and (b) not cause you to panic when all the roads that were there before have disappeared :)

**Comment by georgiashay** [comment]
Bumping up priority due to FireRoad auth changes

**Comment by npfoss** [comment]
closed by #367
