### ISSUE TITLE
Login not working on mobile devices

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#294]
Both courseroad and fireroad login never load for me on mobile devices (android phone/iPad).  I didn't have this problem before but I couldn't pinpoint when it started (sometime after Spring semester).  I can use MIT login on other websites fine.  Is this just a problem with my devices or is anyone else seeing this?

**Comment by venkatesh-sivaraman** [comment]
This might be an OIDC issue - I’ve reached out to them and they’re apparently working on it. It definitely doesn’t affect all users, but I’ve had it happen to me as well. Have you tried leaving it for several minutes and seeing if it loads (or displays an error)?

**Comment by georgiashay** [comment]
If I leave it I get Internal Server Error for oidc, but I think that's after leaving the tab and coming back to it

**Comment by miriam-rittenberg** [comment]
FireRoad now uses Touchstone instead of OIDC
