### ISSUE TITLE
User agent same for different tabs

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#300]
Two different tabs saving a road, observed both with user agent '... Tab 2'.

**Comment by georgiashay** [comment]
Also means impossible to invoke conflicts

**Comment by miriam-rittenberg** [comment]
Different tabs show up as different agents for me (I tried on both Safari and Chrome).

**Comment by npfoss** [comment]
conflicts are definitely not working though, so I'm elevating the priority of this

**Comment by georgiashay** [comment]
I found this issue as part of unit testing for Auth (#303).  I've committed the fix in that branch but it could be a while before it is ready - should I create a quick PR to fix this separately?

**Comment by npfoss** [comment]
Yeah please do. Sorry I'm responding so late but it'll be good to get that in
