### ISSUE TITLE
Access is denied to the MIT people directory unless we send the request through cors-anywhere

### ISSUE THREAD

**Issue by miriam-rittenberg** [sipb/courseroad2#310]
Sending an axios request to https://web.mit.edu/bin/cgicso?query=mrittenb (or any other kerberos username) gives an access-control-allow-origin error unless we send the request through https://cors-anywhere.herokuapp.com/

**Comment by ttpcodes** [comment]
For getting information about someone in the MIT People Directory, there's actually an [official API](https://developer.mit.edu/api-people) that IS&T offers for this, which includes a route that just allows you to enter a `Kerberos` and get the information directly. This is probably a cleaner way to get information from the MIT People Directory versus trying to scrape the public web endpoint and dealing with CORS and other issues.
