### ISSUE TITLE
Google preview text says we are browsing from mobile

### ISSUE THREAD

**Issue by miriam-rittenberg** [sipb/courseroad2#311]
This is the text that shows up under the CourseRoad title when I google CourseRoad:
"It looks like you're browsing CourseRoad from mobile! For a better mobile experience, consider downloading the FireRoad app instead, available on Android..."

**Comment by npfoss** [comment]
hah. that's embarrassing

**Comment by npfoss** [comment]
Ok so it looks like this is still not working:
![image](https://user-images.githubusercontent.com/10506482/67026255-6386f500-f0d5-11e9-8dfd-fb1c56a611ca.png)

Inspecting the raw source of the main page, it's definitely getting exactly what we want (the `index.html` in the root dir):
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <!-- <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto" /> -->
    <title>CourseRoad</title>
  <link href="css/app.css" rel="stylesheet"></head>
  <body>
    <div id="app"></div>
  <script type="text/javascript" src="main.js"></script></body>
</html>
```
(Our most recent test removed the meta tag here)

I did a bit of reading and [this website](https://www.smashingmagazine.com/2019/05/vue-js-seo-reactive-websites-search-engines-bots/) seems to indicate that Google will index basically anything, but my main takeaway is that the `<meta>` tags in `index.html` should really be doing it for us.

So I think from here what we should do is go completely overboard with the meta tags and throw them all in `index.html` and see what happens.
