### ISSUE TITLE
create equivalence pair for 7.30

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#316]
We decided this is the solution but I forget where those moved to. I think it's on the FireRoad side now?

Inspired by this email:
> I’m emailing to submit a problem for Course 7 requirements: for restricted electives, one of the options is to take both 7.30A and 7.30B, but those subjects are no longer offered. Instead, the class is now combined to 7.30(J) – it’s the same class, just combined and a slightly different name.

**Comment by MaximoMachado** [comment]
I emailed venkat and it looks like the issue has been solved. I can also confirm that it is on FireRoad's side now. They have a UI on fireroad.mit.edu that allows them to edit and add to the parsed information.

**Comment by npfoss** [comment]
Thanks! Where on the fireroad site can you edit this? I looked there initially but couldn't find anything besides the degree requirement editor.

**Comment by venkatesh-sivaraman** [comment]
@npfoss this is an admin thing, but I think you should be able to see it since I made you a staff user - make sure you've logged in using the Login button (through OIDC), then click Admin > Catalog Corrections.

**Comment by npfoss** [comment]
Ah I just wasn't looking in the right place. Thanks
