### ISSUE TITLE
duplicate roads cause errors

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#321]
I think I caused this by editing some roads without logging in a while ago, but then logged in from a blank road just now and found all these extra things. If anyone figures out how to reliably reproduce this please comment.

![image](https://user-images.githubusercontent.com/10506482/66257465-96d99380-e767-11e9-8ece-aec040e5351a.png)

**Comment by miriam-rittenberg** [comment]
Whenever I edit a road while not logged in and then log in, I get a warning triangle next to the logout button that says 'My First Road (3): This file already exists on the server. Please try again.' when I mouse over it, but it doesn't show up as an error in the console

**Comment by georgiashay** [comment]
I have seen this before as well but can't reproduce it.  In theory when you log in and have local roads they should be renumbered so this doesn't happen, but I'm wondering if it is trying to load those roads onto the server before checking for name conflicts
