### ISSUE TITLE
Road loading forever

### ISSUE THREAD

**Issue by CyanoKobalamyne** [sipb/courseroad2#326]
When I open my default road (by just going to courseroad.mit.edu), it will show the list of my subjects, however, the left sidebar will only show "loading..." for all of my programs, no matter for how long I wait (I waited for a while). This happens even after removing all programs and adding them back one-by-one (or even just one program).

On the console I can see two related errors, both at `main.js:7:157541`:

```
TypeError: this.roads.$defaultroad$.contents.selectedSubjects.flat is not a function
Stack trace:
getNewRoadData@https://courseroad.mit.edu/main.js:62:56178
cookiesAllowed@https://courseroad.mit.edu/main.js:62:48630
Nn.prototype.run@https://courseroad.mit.edu/main.js:7:34874
Rn@https://courseroad.mit.edu/main.js:7:32524
ve/<@https://courseroad.mit.edu/main.js:7:16434
de@https://courseroad.mit.edu/main.js:7:15876
a@https://courseroad.mit.edu/main.js:62:83487
V/<@https://courseroad.mit.edu/main.js:62:83632
c@https://courseroad.mit.edu/main.js:1422:27666

TypeError: r.selectedSubjects.flat is not a function
Stack trace:
updateFulfillment@https://courseroad.mit.edu/main.js:62:31726
mounted@https://courseroad.mit.edu/main.js:62:30847
ie@https://courseroad.mit.edu/main.js:7:15362
Dn@https://courseroad.mit.edu/main.js:7:32089
insert@https://courseroad.mit.edu/main.js:7:26398
Y@https://courseroad.mit.edu/main.js:7:66911
Wr</<@https://courseroad.mit.edu/main.js:7:69033
t.prototype._update@https://courseroad.mit.edu/main.js:7:43932
Qn.prototype.$mount/</i<@https://courseroad.mit.edu/main.js:7:76875
Nn.prototype.get@https://courseroad.mit.edu/main.js:7:33857
Nn@https://courseroad.mit.edu/main.js:7:33782
Qn.prototype.$mount/<@https://courseroad.mit.edu/main.js:7:76901
Qn.prototype.$mount@https://courseroad.mit.edu/main.js:7:76217
t.prototype._init@https://courseroad.mit.edu/main.js:7:41963
Qn@https://courseroad.mit.edu/main.js:7:38904
@https://courseroad.mit.edu/main.js:1441:12651
D@https://courseroad.mit.edu/main.js:1:7204
i@https://courseroad.mit.edu/main.js:1:565
@https://courseroad.mit.edu/main.js:1422:121
D@https://courseroad.mit.edu/main.js:1:7204
@https://courseroad.mit.edu/main.js:1:8029
@https://courseroad.mit.edu/main.js:1:2
```

**Comment by npfoss** [comment]
Darn. Thanks for bringing this to our attention! A few questions for you:
- Do you use the FireRoad app?
- Has it been a long time since you last used courseroad (before seeing this bug)
- If you log out and log back in does it go away?

**Comment by CyanoKobalamyne** [comment]
I downloaded the app shortly after it was first published, haven't really used it since then. I logged in now, and it still seems to work.

The last time I opened the site was months ago; I don't remember the exact date, sorry.

I tried logging out and in again, hard refreshing, deleting all cookies and site data, to no avail.

**Comment by npfoss** [comment]
Hmm... ok I'm still not sure what it could be, and haven't been able to reproduce it. Can you please export the offending road and either paste the contents here or email it to me? (npfoss@mit)

**Comment by georgiashay** [comment]
This could likely be a browser issue.  .flat() does not work in internet explorer or edge.  We've been focusing on Chrome/Firefox so probably missed this; is the best course of action using the long and unreadable concat.apply thing we had before, or defining a flat function if it is not defined already?

**Comment by CyanoKobalamyne** [comment]
I'm on Firefox (ESR channel).

**Comment by georgiashay** [comment]
What version of Firefox is it?

**Comment by CyanoKobalamyne** [comment]
Sorry, I just updated the comment with the version number.

**Comment by georgiashay** [comment]
Yes, it's definitely possible to change this to support more browsers - should be a simple fix and we'll get it out as soon as possible

**Comment by npfoss** [comment]
@CyanoKobalamyne just deployed the fix for this to the main site, please let us know if it still isn't working. You might have to hard-refresh to clear your cache
