### ISSUE TITLE
`reqList` is an object which we seem to care about the order of

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#363]
```js
        const ordered = {};
        Object.keys(response.data).sort().forEach(function (key) {
          ordered[key] = response.data[key];
        });
        this.reqList = ordered;
```
(taken from `MainPage`)

If we care about the order, this should be a list? I'm confused, so either way it seems some refactoring may be in order.

**Comment by georgiashay** [comment]
It seems like the only use of it uses Object.keys anyway so there should be no reason not to make it a list
