### ISSUE TITLE
Subjects never load for imported roads

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#366]
![image](https://user-images.githubusercontent.com/33201801/73139982-bf9cd600-4041-11ea-94a6-f0297b7c9e3a.png)

Error briefly shows up in dialog when importing, too quick to see but could just be duplicate name error as it is adding the road.  No errors in console and road seems to disappear on refresh.

**Comment by ttpcodes** [comment]
This issue should be resolved by #382.

**Comment by georgiashay** [comment]
I'm not seeing this behavior anymore on master
