### ISSUE TITLE
override warnings doesn't happen if you don't click 'close'

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#402]
If you click on the triangle and toggle the switch but then press esc to close the dialog, your change doesn't actually take effect, however if you open the dialog again, the toggle will look like you indeed switched it. (e.g. I click override warning then esc --> triangle still there --> click triangle again --> see that toggle is already on --> ???)

**Comment by yimmt** [comment]
I also like to say the 'close' refers to button with "close" text. If you decide to press button with the close icon, the same bug applies.
