### ISSUE TITLE
Some fireroad urls failing

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#434]
Fireroad urls in the audit are failing.  Occurs on dev and prod.  Unclear if this is a fireroad-side issue or a courseroad-side issue.

**Comment by georgiashay** [comment]
The urls appear to be failing when you add manual progress

**Comment by venkatesh-sivaraman** [comment]
Looks like this is a FireRoad issue related to the recent PR - I [filed an issue](https://github.com/venkatesh-sivaraman/fireroad-server/issues/23) with a stack trace

**Comment by georgiashay** [comment]
Fixed on fireroad-server
